version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9999:3000"
    environment:
      NODE_ENV: production
      PGUSER: db_user
      PGHOST: 0.0.0.0
      PGPASSWORD: supersecretpwdhere
      PGDATABASE: myDB
      PGPORT: 5432
      DATABASE_URL: postgres://myuser@postgres/testdb
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: myuser
